# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/design002.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabInfo = QtWidgets.QWidget()
        self.tabInfo.setObjectName("tabInfo")
        self.confArea = QtWidgets.QListWidget(self.tabInfo)
        self.confArea.setGeometry(QtCore.QRect(10, 240, 211, 221))
        self.confArea.setObjectName("confArea")
        self.label_4 = QtWidgets.QLabel(self.tabInfo)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 101, 51))
        self.label_4.setObjectName("label_4")
        self.refreshHostsButton = QtWidgets.QPushButton(self.tabInfo)
        self.refreshHostsButton.setGeometry(QtCore.QRect(230, 240, 211, 33))
        self.refreshHostsButton.setObjectName("refreshHostsButton")
        self.tableProjects = QtWidgets.QTableWidget(self.tabInfo)
        self.tableProjects.setGeometry(QtCore.QRect(10, 40, 751, 192))
        self.tableProjects.setObjectName("tableProjects")
        self.tableProjects.setColumnCount(0)
        self.tableProjects.setRowCount(0)
        self.tabWidget.addTab(self.tabInfo, "")
        self.tabCreate = QtWidgets.QWidget()
        self.tabCreate.setObjectName("tabCreate")
        self.label_3 = QtWidgets.QLabel(self.tabCreate)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 168, 34))
        self.label_3.setObjectName("label_3")
        self.createProjectButton = QtWidgets.QPushButton(self.tabCreate)
        self.createProjectButton.setGeometry(QtCore.QRect(260, 260, 171, 33))
        self.createProjectButton.setObjectName("createProjectButton")
        self.label_2 = QtWidgets.QLabel(self.tabCreate)
        self.label_2.setGeometry(QtCore.QRect(260, 71, 75, 17))
        self.label_2.setObjectName("label_2")
        self.chooseWWWButton = QtWidgets.QPushButton(self.tabCreate)
        self.chooseWWWButton.setGeometry(QtCore.QRect(730, 210, 31, 33))
        self.chooseWWWButton.setObjectName("chooseWWWButton")
        self.label_6 = QtWidgets.QLabel(self.tabCreate)
        self.label_6.setGeometry(QtCore.QRect(550, 70, 75, 17))
        self.label_6.setObjectName("label_6")
        self.chooseFolderButton = QtWidgets.QPushButton(self.tabCreate)
        self.chooseFolderButton.setGeometry(QtCore.QRect(730, 150, 31, 33))
        self.chooseFolderButton.setObjectName("chooseFolderButton")
        self.label_7 = QtWidgets.QLabel(self.tabCreate)
        self.label_7.setGeometry(QtCore.QRect(550, 0, 101, 17))
        self.label_7.setObjectName("label_7")
        self.projrctFolderLine = QtWidgets.QLineEdit(self.tabCreate)
        self.projrctFolderLine.setGeometry(QtCore.QRect(260, 150, 461, 33))
        self.projrctFolderLine.setObjectName("projrctFolderLine")
        self.radioExistFolder = QtWidgets.QRadioButton(self.tabCreate)
        self.radioExistFolder.setGeometry(QtCore.QRect(250, 30, 141, 23))
        self.radioExistFolder.setObjectName("radioExistFolder")
        self.repositoryLine = QtWidgets.QLineEdit(self.tabCreate)
        self.repositoryLine.setGeometry(QtCore.QRect(550, 25, 211, 33))
        self.repositoryLine.setObjectName("repositoryLine")
        self.projectNameLine = QtWidgets.QLineEdit(self.tabCreate)
        self.projectNameLine.setGeometry(QtCore.QRect(260, 90, 281, 33))
        self.projectNameLine.setObjectName("projectNameLine")
        self.label = QtWidgets.QLabel(self.tabCreate)
        self.label.setGeometry(QtCore.QRect(260, 130, 191, 17))
        self.label.setObjectName("label")
        self.hostLine = QtWidgets.QLineEdit(self.tabCreate)
        self.hostLine.setGeometry(QtCore.QRect(550, 90, 211, 33))
        self.hostLine.setObjectName("hostLine")
        self.label_5 = QtWidgets.QLabel(self.tabCreate)
        self.label_5.setGeometry(QtCore.QRect(260, 190, 101, 17))
        self.label_5.setObjectName("label_5")
        self.radioGit = QtWidgets.QRadioButton(self.tabCreate)
        self.radioGit.setGeometry(QtCore.QRect(400, 30, 141, 23))
        self.radioGit.setObjectName("radioGit")
        self.projrctWWWrLine = QtWidgets.QLineEdit(self.tabCreate)
        self.projrctWWWrLine.setGeometry(QtCore.QRect(260, 210, 461, 33))
        self.projrctWWWrLine.setObjectName("projrctWWWrLine")
        self.tabWidget.addTab(self.tabCreate, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python3 LAMP GUI MANAGER v0.0.1"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Projects</span></p></body></html>"))
        self.refreshHostsButton.setText(_translate("MainWindow", "Refresh Hosts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfo), _translate("MainWindow", "Info"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Project create</span></p></body></html>"))
        self.createProjectButton.setText(_translate("MainWindow", "Create"))
        self.label_2.setText(_translate("MainWindow", "Project name"))
        self.chooseWWWButton.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "Host name"))
        self.chooseFolderButton.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Git link (only ssh)"))
        self.radioExistFolder.setText(_translate("MainWindow", "From existing folder"))
        self.label.setText(_translate("MainWindow", "Project folder(if git Projects folder)"))
        self.label_5.setText(_translate("MainWindow", "public_html/www"))
        self.radioGit.setText(_translate("MainWindow", "From git repository"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCreate), _translate("MainWindow", "Create host"))

