# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/design003.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabInfo = QtWidgets.QWidget()
        self.tabInfo.setObjectName("tabInfo")
        self.treeServersProjects = QtWidgets.QTreeWidget(self.tabInfo)
        self.treeServersProjects.setGeometry(QtCore.QRect(-2, 0, 256, 521))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 159, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.treeServersProjects.setPalette(palette)
        self.treeServersProjects.setObjectName("treeServersProjects")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeServersProjects)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeServersProjects)
        self.projrctWWWrLine = QtWidgets.QLineEdit(self.tabInfo)
        self.projrctWWWrLine.setGeometry(QtCore.QRect(260, 240, 461, 33))
        self.projrctWWWrLine.setObjectName("projrctWWWrLine")
        self.projrctFolderLine = QtWidgets.QLineEdit(self.tabInfo)
        self.projrctFolderLine.setGeometry(QtCore.QRect(260, 180, 461, 33))
        self.projrctFolderLine.setObjectName("projrctFolderLine")
        self.hostLine = QtWidgets.QLineEdit(self.tabInfo)
        self.hostLine.setGeometry(QtCore.QRect(260, 120, 251, 33))
        self.hostLine.setObjectName("hostLine")
        self.saveProjectButton = QtWidgets.QPushButton(self.tabInfo)
        self.saveProjectButton.setGeometry(QtCore.QRect(260, 410, 131, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 202, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 202, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 243, 243))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 202, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.saveProjectButton.setPalette(palette)
        self.saveProjectButton.setObjectName("saveProjectButton")
        self.chooseWWWButton = QtWidgets.QPushButton(self.tabInfo)
        self.chooseWWWButton.setGeometry(QtCore.QRect(730, 240, 31, 33))
        self.chooseWWWButton.setObjectName("chooseWWWButton")
        self.repositoryLine = QtWidgets.QLineEdit(self.tabInfo)
        self.repositoryLine.setGeometry(QtCore.QRect(520, 60, 241, 33))
        self.repositoryLine.setObjectName("repositoryLine")
        self.chooseFolderButton = QtWidgets.QPushButton(self.tabInfo)
        self.chooseFolderButton.setGeometry(QtCore.QRect(730, 180, 31, 33))
        self.chooseFolderButton.setObjectName("chooseFolderButton")
        self.label_7 = QtWidgets.QLabel(self.tabInfo)
        self.label_7.setGeometry(QtCore.QRect(520, 40, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.projectNameLine = QtWidgets.QLineEdit(self.tabInfo)
        self.projectNameLine.setGeometry(QtCore.QRect(260, 60, 251, 33))
        self.projectNameLine.setObjectName("projectNameLine")
        self.label_2 = QtWidgets.QLabel(self.tabInfo)
        self.label_2.setGeometry(QtCore.QRect(260, 41, 91, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.tabInfo)
        self.label_6.setGeometry(QtCore.QRect(260, 100, 75, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.tabInfo)
        self.label.setGeometry(QtCore.QRect(260, 160, 211, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.tabInfo)
        self.label_5.setGeometry(QtCore.QRect(260, 220, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineIP = QtWidgets.QLineEdit(self.tabInfo)
        self.lineIP.setGeometry(QtCore.QRect(520, 120, 181, 33))
        self.lineIP.setObjectName("lineIP")
        self.linePort = QtWidgets.QLineEdit(self.tabInfo)
        self.linePort.setGeometry(QtCore.QRect(700, 120, 61, 33))
        self.linePort.setObjectName("linePort")
        self.label_8 = QtWidgets.QLabel(self.tabInfo)
        self.label_8.setGeometry(QtCore.QRect(520, 100, 75, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tabInfo)
        self.label_9.setGeometry(QtCore.QRect(700, 100, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tabInfo)
        self.label_10.setGeometry(QtCore.QRect(260, 280, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.checkBoxCreateDatabase = QtWidgets.QCheckBox(self.tabInfo)
        self.checkBoxCreateDatabase.setGeometry(QtCore.QRect(260, 305, 151, 23))
        self.checkBoxCreateDatabase.setObjectName("checkBoxCreateDatabase")
        self.lineNewDatabase = QtWidgets.QLineEdit(self.tabInfo)
        self.lineNewDatabase.setGeometry(QtCore.QRect(410, 300, 171, 33))
        self.lineNewDatabase.setObjectName("lineNewDatabase")
        self.comboSelectDatabase = QtWidgets.QComboBox(self.tabInfo)
        self.comboSelectDatabase.setGeometry(QtCore.QRect(590, 300, 171, 33))
        self.comboSelectDatabase.setObjectName("comboSelectDatabase")
        self.comboPhpApache = QtWidgets.QComboBox(self.tabInfo)
        self.comboPhpApache.setGeometry(QtCore.QRect(480, 360, 93, 33))
        self.comboPhpApache.setObjectName("comboPhpApache")
        self.label_12 = QtWidgets.QLabel(self.tabInfo)
        self.label_12.setGeometry(QtCore.QRect(490, 340, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tabInfo)
        self.label_13.setGeometry(QtCore.QRect(606, 340, 41, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.comboPhpCli = QtWidgets.QComboBox(self.tabInfo)
        self.comboPhpCli.setGeometry(QtCore.QRect(580, 360, 93, 33))
        self.comboPhpCli.setObjectName("comboPhpCli")
        self.pushPhpIni = QtWidgets.QPushButton(self.tabInfo)
        self.pushPhpIni.setGeometry(QtCore.QRect(680, 360, 81, 33))
        self.pushPhpIni.setObjectName("pushPhpIni")
        self.pushPull = QtWidgets.QPushButton(self.tabInfo)
        self.pushPull.setGeometry(QtCore.QRect(600, 410, 81, 33))
        self.pushPull.setAutoFillBackground(False)
        self.pushPull.setObjectName("pushPull")
        self.pushGitAddCommit = QtWidgets.QPushButton(self.tabInfo)
        self.pushGitAddCommit.setGeometry(QtCore.QRect(400, 410, 111, 33))
        self.pushGitAddCommit.setObjectName("pushGitAddCommit")
        self.pushGitPush = QtWidgets.QPushButton(self.tabInfo)
        self.pushGitPush.setGeometry(QtCore.QRect(520, 410, 71, 33))
        self.pushGitPush.setObjectName("pushGitPush")
        self.pushStash = QtWidgets.QPushButton(self.tabInfo)
        self.pushStash.setGeometry(QtCore.QRect(690, 410, 71, 33))
        self.pushStash.setObjectName("pushStash")
        self.textCommandsResponce = QtWidgets.QTextEdit(self.tabInfo)
        self.textCommandsResponce.setGeometry(QtCore.QRect(260, 450, 501, 61))
        self.textCommandsResponce.setObjectName("textCommandsResponce")
        self.label_14 = QtWidgets.QLabel(self.tabInfo)
        self.label_14.setGeometry(QtCore.QRect(700, 340, 41, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pushPullDeleteProj = QtWidgets.QPushButton(self.tabInfo)
        self.pushPullDeleteProj.setGeometry(QtCore.QRect(660, 10, 91, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushPullDeleteProj.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushPullDeleteProj.setFont(font)
        self.pushPullDeleteProj.setAutoFillBackground(False)
        self.pushPullDeleteProj.setObjectName("pushPullDeleteProj")
        self.groupProjStatus = QtWidgets.QGroupBox(self.tabInfo)
        self.groupProjStatus.setGeometry(QtCore.QRect(260, 0, 120, 41))
        self.groupProjStatus.setObjectName("groupProjStatus")
        self.radioButtonProjOn = QtWidgets.QRadioButton(self.groupProjStatus)
        self.radioButtonProjOn.setGeometry(QtCore.QRect(10, 20, 51, 23))
        self.radioButtonProjOn.setObjectName("radioButtonProjOn")
        self.radioButtonProjOff = QtWidgets.QRadioButton(self.groupProjStatus)
        self.radioButtonProjOff.setGeometry(QtCore.QRect(60, 20, 51, 23))
        self.radioButtonProjOff.setObjectName("radioButtonProjOff")
        self.groupProjCreate = QtWidgets.QGroupBox(self.tabInfo)
        self.groupProjCreate.setGeometry(QtCore.QRect(370, 0, 281, 41))
        self.groupProjCreate.setObjectName("groupProjCreate")
        self.radioExistFolder = QtWidgets.QRadioButton(self.groupProjCreate)
        self.radioExistFolder.setGeometry(QtCore.QRect(10, 20, 131, 23))
        self.radioExistFolder.setObjectName("radioExistFolder")
        self.radioGit = QtWidgets.QRadioButton(self.groupProjCreate)
        self.radioGit.setGeometry(QtCore.QRect(130, 20, 141, 23))
        self.radioGit.setObjectName("radioGit")
        self.groupFrame = QtWidgets.QGroupBox(self.tabInfo)
        self.groupFrame.setGeometry(QtCore.QRect(251, 340, 211, 80))
        self.groupFrame.setObjectName("groupFrame")
        self.radioYii = QtWidgets.QRadioButton(self.groupFrame)
        self.radioYii.setGeometry(QtCore.QRect(70, 30, 51, 23))
        self.radioYii.setObjectName("radioYii")
        self.radioWP = QtWidgets.QRadioButton(self.groupFrame)
        self.radioWP.setGeometry(QtCore.QRect(120, 30, 98, 23))
        self.radioWP.setObjectName("radioWP")
        self.radioLuya = QtWidgets.QRadioButton(self.groupFrame)
        self.radioLuya.setGeometry(QtCore.QRect(10, 30, 61, 23))
        self.radioLuya.setObjectName("radioLuya")
        self.tabWidget.addTab(self.tabInfo, "")
        self.tabCreate = QtWidgets.QWidget()
        self.tabCreate.setObjectName("tabCreate")
        self.comboProjectTools = QtWidgets.QComboBox(self.tabCreate)
        self.comboProjectTools.setGeometry(QtCore.QRect(60, 2, 171, 33))
        self.comboProjectTools.setObjectName("comboProjectTools")
        self.label_3 = QtWidgets.QLabel(self.tabCreate)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 41, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textProjectInfo = QtWidgets.QTextEdit(self.tabCreate)
        self.textProjectInfo.setGeometry(QtCore.QRect(10, 40, 221, 241))
        self.textProjectInfo.setObjectName("textProjectInfo")
        self.pushButtonGenBase = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonGenBase.setGeometry(QtCore.QRect(10, 430, 221, 33))
        self.pushButtonGenBase.setObjectName("pushButtonGenBase")
        self.plainTerminal = QtWidgets.QPlainTextEdit(self.tabCreate)
        self.plainTerminal.setGeometry(QtCore.QRect(237, 40, 521, 241))
        self.plainTerminal.setObjectName("plainTerminal")
        self.label_4 = QtWidgets.QLabel(self.tabCreate)
        self.label_4.setGeometry(QtCore.QRect(240, 10, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButtonComposerIn = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonComposerIn.setGeometry(QtCore.QRect(645, 290, 111, 33))
        self.pushButtonComposerIn.setObjectName("pushButtonComposerIn")
        self.pushButtonComposerUp = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonComposerUp.setGeometry(QtCore.QRect(530, 290, 111, 33))
        self.pushButtonComposerUp.setObjectName("pushButtonComposerUp")
        self.pushButtonMigrate = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonMigrate.setGeometry(QtCore.QRect(434, 290, 91, 33))
        self.pushButtonMigrate.setObjectName("pushButtonMigrate")
        self.pushButtonImport = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonImport.setGeometry(QtCore.QRect(340, 290, 91, 33))
        self.pushButtonImport.setObjectName("pushButtonImport")
        self.pushButtonCreateUserFrame = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonCreateUserFrame.setGeometry(QtCore.QRect(236, 290, 101, 33))
        self.pushButtonCreateUserFrame.setObjectName("pushButtonCreateUserFrame")
        self.label_15 = QtWidgets.QLabel(self.tabCreate)
        self.label_15.setGeometry(QtCore.QRect(20, 330, 71, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tabCreate)
        self.label_16.setGeometry(QtCore.QRect(160, 330, 41, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.pushButtonGitStashTools = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonGitStashTools.setGeometry(QtCore.QRect(693, 430, 61, 33))
        self.pushButtonGitStashTools.setObjectName("pushButtonGitStashTools")
        self.comboPHPCliTools = QtWidgets.QComboBox(self.tabCreate)
        self.comboPHPCliTools.setGeometry(QtCore.QRect(126, 350, 101, 33))
        self.comboPHPCliTools.setObjectName("comboPHPCliTools")
        self.comboPHPATolls = QtWidgets.QComboBox(self.tabCreate)
        self.comboPHPATolls.setGeometry(QtCore.QRect(10, 350, 101, 33))
        self.comboPHPATolls.setObjectName("comboPHPATolls")
        self.lineEditNewBaseTools = QtWidgets.QLineEdit(self.tabCreate)
        self.lineEditNewBaseTools.setGeometry(QtCore.QRect(400, 430, 131, 33))
        self.lineEditNewBaseTools.setObjectName("lineEditNewBaseTools")
        self.pushButtonGitAddComText = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonGitAddComText.setGeometry(QtCore.QRect(537, 390, 111, 33))
        self.pushButtonGitAddComText.setObjectName("pushButtonGitAddComText")
        self.pushButtonPHPSetTool = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonPHPSetTool.setGeometry(QtCore.QRect(10, 390, 221, 33))
        self.pushButtonPHPSetTool.setObjectName("pushButtonPHPSetTool")
        self.pushButtonGitPushTools = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonGitPushTools.setGeometry(QtCore.QRect(537, 430, 71, 33))
        self.pushButtonGitPushTools.setObjectName("pushButtonGitPushTools")
        self.comboBoxEncoding = QtWidgets.QComboBox(self.tabCreate)
        self.comboBoxEncoding.setGeometry(QtCore.QRect(400, 470, 61, 33))
        self.comboBoxEncoding.setObjectName("comboBoxEncoding")
        self.pushButtonEditConfigA = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonEditConfigA.setGeometry(QtCore.QRect(120, 290, 111, 33))
        self.pushButtonEditConfigA.setObjectName("pushButtonEditConfigA")
        self.pushButtonRestartA = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonRestartA.setGeometry(QtCore.QRect(10, 290, 101, 33))
        self.pushButtonRestartA.setObjectName("pushButtonRestartA")
        self.label_19 = QtWidgets.QLabel(self.tabCreate)
        self.label_19.setGeometry(QtCore.QRect(240, 410, 61, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButtonCreateBaseTools = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonCreateBaseTools.setGeometry(QtCore.QRect(470, 470, 61, 33))
        self.pushButtonCreateBaseTools.setObjectName("pushButtonCreateBaseTools")
        self.comboBoxBaseSelectTools = QtWidgets.QComboBox(self.tabCreate)
        self.comboBoxBaseSelectTools.setGeometry(QtCore.QRect(240, 430, 151, 33))
        self.comboBoxBaseSelectTools.setObjectName("comboBoxBaseSelectTools")
        self.pushButtonDeploy = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonDeploy.setGeometry(QtCore.QRect(664, 470, 91, 33))
        self.pushButtonDeploy.setObjectName("pushButtonDeploy")
        self.pushButtonGitPullTools = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonGitPullTools.setGeometry(QtCore.QRect(614, 430, 71, 33))
        self.pushButtonGitPullTools.setAutoFillBackground(False)
        self.pushButtonGitPullTools.setObjectName("pushButtonGitPullTools")
        self.pushButtonPHPMyAdmin = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonPHPMyAdmin.setGeometry(QtCore.QRect(10, 470, 221, 33))
        self.pushButtonPHPMyAdmin.setObjectName("pushButtonPHPMyAdmin")
        self.pushButtonProxy = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonProxy.setGeometry(QtCore.QRect(236, 329, 101, 33))
        self.pushButtonProxy.setObjectName("pushButtonProxy")
        self.pushButtonModule = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonModule.setGeometry(QtCore.QRect(340, 329, 91, 33))
        self.pushButtonModule.setObjectName("pushButtonModule")
        self.pushButtonMigcreate = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonMigcreate.setGeometry(QtCore.QRect(434, 329, 91, 33))
        self.pushButtonMigcreate.setObjectName("pushButtonMigcreate")
        self.label_21 = QtWidgets.QLabel(self.tabCreate)
        self.label_21.setGeometry(QtCore.QRect(400, 410, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.pushButtonDump = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonDump.setGeometry(QtCore.QRect(240, 470, 61, 33))
        self.pushButtonDump.setObjectName("pushButtonDump")
        self.pushButtonDeleteBase = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonDeleteBase.setGeometry(QtCore.QRect(310, 470, 81, 33))
        self.pushButtonDeleteBase.setObjectName("pushButtonDeleteBase")
        self.pushButtonTerminalClear = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonTerminalClear.setGeometry(QtCore.QRect(434, 370, 91, 33))
        self.pushButtonTerminalClear.setObjectName("pushButtonTerminalClear")
        self.pushButtonFramework = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonFramework.setGeometry(QtCore.QRect(340, 370, 91, 33))
        self.pushButtonFramework.setObjectName("pushButtonFramework")
        self.pushButtonChmod = QtWidgets.QPushButton(self.tabCreate)
        self.pushButtonChmod.setGeometry(QtCore.QRect(236, 370, 101, 33))
        self.pushButtonChmod.setObjectName("pushButtonChmod")
        self.lineEditCommit = QtWidgets.QLineEdit(self.tabCreate)
        self.lineEditCommit.setGeometry(QtCore.QRect(649, 390, 106, 33))
        self.lineEditCommit.setObjectName("lineEditCommit")
        self.textEditGitStatus = QtWidgets.QTextEdit(self.tabCreate)
        self.textEditGitStatus.setGeometry(QtCore.QRect(537, 330, 219, 55))
        self.textEditGitStatus.setObjectName("textEditGitStatus")
        self.comboBoxGitBranch = QtWidgets.QComboBox(self.tabCreate)
        self.comboBoxGitBranch.setGeometry(QtCore.QRect(537, 470, 120, 33))
        self.comboBoxGitBranch.setObjectName("comboBoxGitBranch")
        self.tabWidget.addTab(self.tabCreate, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowserLogErrA = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowserLogErrA.setGeometry(QtCore.QRect(20, 30, 731, 101))
        self.textBrowserLogErrA.setObjectName("textBrowserLogErrA")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(20, 10, 91, 17))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(20, 140, 91, 17))
        self.label_30.setObjectName("label_30")
        self.textBrowserLogAccA = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowserLogAccA.setGeometry(QtCore.QRect(20, 160, 731, 101))
        self.textBrowserLogAccA.setObjectName("textBrowserLogAccA")
        self.label_31 = QtWidgets.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(20, 280, 54, 17))
        self.label_31.setObjectName("label_31")
        self.textBrowserPHPlog = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowserPHPlog.setGeometry(QtCore.QRect(20, 310, 731, 101))
        self.textBrowserPHPlog.setObjectName("textBrowserPHPlog")
        self.comboBoxPHPLog = QtWidgets.QComboBox(self.tab_2)
        self.comboBoxPHPLog.setGeometry(QtCore.QRect(50, 270, 93, 33))
        self.comboBoxPHPLog.setObjectName("comboBoxPHPLog")
        self.textBrowserLogMysql = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowserLogMysql.setGeometry(QtCore.QRect(20, 440, 731, 71))
        self.textBrowserLogMysql.setObjectName("textBrowserLogMysql")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(23, 422, 54, 17))
        self.label_32.setObjectName("label_32")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(660, 270, 88, 33))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.label_17.setObjectName("label_17")
        self.lineEditApacheFolder = QtWidgets.QLineEdit(self.tab)
        self.lineEditApacheFolder.setGeometry(QtCore.QRect(130, 13, 271, 33))
        self.lineEditApacheFolder.setObjectName("lineEditApacheFolder")
        self.toolButton = QtWidgets.QToolButton(self.tab)
        self.toolButton.setGeometry(QtCore.QRect(408, 13, 32, 33))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.tab)
        self.toolButton_2.setGeometry(QtCore.QRect(408, 50, 32, 33))
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(20, 57, 101, 17))
        self.label_18.setObjectName("label_18")
        self.lineEditPHPFolder = QtWidgets.QLineEdit(self.tab)
        self.lineEditPHPFolder.setGeometry(QtCore.QRect(130, 50, 271, 33))
        self.lineEditPHPFolder.setObjectName("lineEditPHPFolder")
        self.toolButton_3 = QtWidgets.QToolButton(self.tab)
        self.toolButton_3.setGeometry(QtCore.QRect(408, 90, 32, 33))
        self.toolButton_3.setObjectName("toolButton_3")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(20, 97, 101, 17))
        self.label_20.setObjectName("label_20")
        self.lineEditLogFolder = QtWidgets.QLineEdit(self.tab)
        self.lineEditLogFolder.setGeometry(QtCore.QRect(130, 90, 271, 33))
        self.lineEditLogFolder.setObjectName("lineEditLogFolder")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(470, 20, 101, 17))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(470, 57, 61, 17))
        self.label_23.setObjectName("label_23")
        self.lineEditMSQLHost = QtWidgets.QLineEdit(self.tab)
        self.lineEditMSQLHost.setGeometry(QtCore.QRect(500, 50, 141, 33))
        self.lineEditMSQLHost.setObjectName("lineEditMSQLHost")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(470, 97, 101, 17))
        self.label_24.setObjectName("label_24")
        self.lineEditMSUser = QtWidgets.QLineEdit(self.tab)
        self.lineEditMSUser.setGeometry(QtCore.QRect(500, 90, 141, 33))
        self.lineEditMSUser.setObjectName("lineEditMSUser")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(470, 137, 101, 17))
        self.label_25.setObjectName("label_25")
        self.lineEditMSPass = QtWidgets.QLineEdit(self.tab)
        self.lineEditMSPass.setGeometry(QtCore.QRect(500, 130, 141, 33))
        self.lineEditMSPass.setObjectName("lineEditMSPass")
        self.lineEditMSPort = QtWidgets.QLineEdit(self.tab)
        self.lineEditMSPort.setGeometry(QtCore.QRect(640, 50, 61, 33))
        self.lineEditMSPort.setObjectName("lineEditMSPort")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(640, 30, 61, 17))
        self.label_26.setObjectName("label_26")
        self.pushButtonMSUserAdd = QtWidgets.QPushButton(self.tab)
        self.pushButtonMSUserAdd.setGeometry(QtCore.QRect(640, 90, 61, 33))
        self.pushButtonMSUserAdd.setObjectName("pushButtonMSUserAdd")
        self.pushButtonMSTest = QtWidgets.QPushButton(self.tab)
        self.pushButtonMSTest.setGeometry(QtCore.QRect(640, 130, 61, 33))
        self.pushButtonMSTest.setObjectName("pushButtonMSTest")
        self.buttonBoxSettings = QtWidgets.QDialogButtonBox(self.tab)
        self.buttonBoxSettings.setGeometry(QtCore.QRect(220, 220, 361, 33))
        self.buttonBoxSettings.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Save)
        self.buttonBoxSettings.setObjectName("buttonBoxSettings")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(320, 260, 151, 17))
        self.label_27.setObjectName("label_27")
        self.comboMSDefEnc = QtWidgets.QComboBox(self.tab)
        self.comboMSDefEnc.setGeometry(QtCore.QRect(500, 170, 141, 33))
        self.comboMSDefEnc.setObjectName("comboMSDefEnc")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(401, 178, 101, 17))
        self.label_28.setObjectName("label_28")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python3 LAMP GUI MANAGER v0.0.1"))
        self.treeServersProjects.headerItem().setText(0, _translate("MainWindow", "Projects & Servers"))
        __sortingEnabled = self.treeServersProjects.isSortingEnabled()
        self.treeServersProjects.setSortingEnabled(False)
        self.treeServersProjects.topLevelItem(0).setText(0, _translate("MainWindow", "Apache"))
        self.treeServersProjects.topLevelItem(1).setText(0, _translate("MainWindow", "MySQL"))
        self.treeServersProjects.setSortingEnabled(__sortingEnabled)
        self.saveProjectButton.setText(_translate("MainWindow", "Save"))
        self.chooseWWWButton.setText(_translate("MainWindow", "..."))
        self.chooseFolderButton.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Git link (only ssh)"))
        self.label_2.setText(_translate("MainWindow", "Project name"))
        self.label_6.setText(_translate("MainWindow", "Host name"))
        self.label.setText(_translate("MainWindow", "Project folder(if git Projects folder)"))
        self.label_5.setText(_translate("MainWindow", "public_html/www"))
        self.label_8.setText(_translate("MainWindow", "IP address"))
        self.label_9.setText(_translate("MainWindow", "Port"))
        self.label_10.setText(_translate("MainWindow", "Database"))
        self.checkBoxCreateDatabase.setText(_translate("MainWindow", "Create new database"))
        self.label_12.setText(_translate("MainWindow", "PHP Apache"))
        self.label_13.setText(_translate("MainWindow", "PHP cli"))
        self.pushPhpIni.setText(_translate("MainWindow", "Settings"))
        self.pushPull.setText(_translate("MainWindow", "Git Pull"))
        self.pushGitAddCommit.setText(_translate("MainWindow", "Git Add + Commit"))
        self.pushGitPush.setText(_translate("MainWindow", "Git Push"))
        self.pushStash.setText(_translate("MainWindow", "Git Stash"))
        self.label_14.setText(_translate("MainWindow", "PHP ini"))
        self.pushPullDeleteProj.setText(_translate("MainWindow", "Delete Project"))
        self.groupProjStatus.setTitle(_translate("MainWindow", "Project Status"))
        self.radioButtonProjOn.setText(_translate("MainWindow", "On"))
        self.radioButtonProjOff.setText(_translate("MainWindow", "Off"))
        self.groupProjCreate.setTitle(_translate("MainWindow", "Create Project"))
        self.radioExistFolder.setText(_translate("MainWindow", "From existed"))
        self.radioGit.setText(_translate("MainWindow", "From git repository"))
        self.groupFrame.setTitle(_translate("MainWindow", "Framework/CMS"))
        self.radioYii.setText(_translate("MainWindow", "Yii2"))
        self.radioWP.setText(_translate("MainWindow", "WordPress"))
        self.radioLuya.setText(_translate("MainWindow", "Luya"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfo), _translate("MainWindow", "Projects && Servers"))
        self.label_3.setText(_translate("MainWindow", "Project"))
        self.pushButtonGenBase.setText(_translate("MainWindow", "Generete Database config file"))
        self.label_4.setText(_translate("MainWindow", "Terminal"))
        self.pushButtonComposerIn.setText(_translate("MainWindow", "Composer install"))
        self.pushButtonComposerUp.setText(_translate("MainWindow", "Composer update"))
        self.pushButtonMigrate.setText(_translate("MainWindow", "Migrate"))
        self.pushButtonImport.setText(_translate("MainWindow", "Import"))
        self.pushButtonCreateUserFrame.setText(_translate("MainWindow", "Create user"))
        self.label_15.setText(_translate("MainWindow", "PHP Apache"))
        self.label_16.setText(_translate("MainWindow", "PHP cli"))
        self.pushButtonGitStashTools.setText(_translate("MainWindow", "Git Stash"))
        self.pushButtonGitAddComText.setText(_translate("MainWindow", "Git Add + Commit:"))
        self.pushButtonPHPSetTool.setText(_translate("MainWindow", "PHP settings"))
        self.pushButtonGitPushTools.setText(_translate("MainWindow", "Git Push"))
        self.pushButtonEditConfigA.setText(_translate("MainWindow", "Host config"))
        self.pushButtonRestartA.setText(_translate("MainWindow", "Restart Apache"))
        self.label_19.setText(_translate("MainWindow", "Database"))
        self.pushButtonCreateBaseTools.setText(_translate("MainWindow", "Create"))
        self.pushButtonDeploy.setText(_translate("MainWindow", "Deploy"))
        self.pushButtonGitPullTools.setText(_translate("MainWindow", "Git Pull"))
        self.pushButtonPHPMyAdmin.setText(_translate("MainWindow", "PhpMyAdmin"))
        self.pushButtonProxy.setText(_translate("MainWindow", "Proxy Admin"))
        self.pushButtonModule.setText(_translate("MainWindow", "Module create"))
        self.pushButtonMigcreate.setText(_translate("MainWindow", "Migrate create"))
        self.label_21.setText(_translate("MainWindow", "New"))
        self.pushButtonDump.setText(_translate("MainWindow", "Dump"))
        self.pushButtonDeleteBase.setText(_translate("MainWindow", "Delete"))
        self.pushButtonTerminalClear.setText(_translate("MainWindow", "Terminal Clear"))
        self.pushButtonFramework.setText(_translate("MainWindow", "./luya | ./yii"))
        self.pushButtonChmod.setText(_translate("MainWindow", "Chmod 777"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCreate), _translate("MainWindow", "Tools"))
        self.label_29.setText(_translate("MainWindow", "Error - Apache"))
        self.label_30.setText(_translate("MainWindow", "Access - Apache"))
        self.label_31.setText(_translate("MainWindow", "PHP"))
        self.label_32.setText(_translate("MainWindow", "MySQL"))
        self.pushButton.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Logs"))
        self.label_17.setText(_translate("MainWindow", "Apache2 directory"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.label_18.setText(_translate("MainWindow", "PHP directory"))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.label_20.setText(_translate("MainWindow", "Log directory"))
        self.label_22.setText(_translate("MainWindow", "MySQL"))
        self.label_23.setText(_translate("MainWindow", "host"))
        self.label_24.setText(_translate("MainWindow", "user"))
        self.label_25.setText(_translate("MainWindow", "pass"))
        self.label_26.setText(_translate("MainWindow", "port"))
        self.pushButtonMSUserAdd.setText(_translate("MainWindow", "+"))
        self.pushButtonMSTest.setText(_translate("MainWindow", "Test"))
        self.label_27.setText(_translate("MainWindow", "Telegram @deepdarkman"))
        self.label_28.setText(_translate("MainWindow", "Default encoding"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings"))

