# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design001.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.confArea = QtWidgets.QListWidget(self.centralwidget)
        self.confArea.setGeometry(QtCore.QRect(10, 52, 211, 221))
        self.confArea.setObjectName("confArea")
        self.chooseFolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseFolderButton.setGeometry(QtCore.QRect(740, 180, 31, 33))
        self.chooseFolderButton.setObjectName("chooseFolderButton")
        self.projrctFolderLine = QtWidgets.QLineEdit(self.centralwidget)
        self.projrctFolderLine.setGeometry(QtCore.QRect(270, 180, 461, 33))
        self.projrctFolderLine.setObjectName("projrctFolderLine")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 160, 191, 17))
        self.label.setObjectName("label")
        self.projectNameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.projectNameLine.setGeometry(QtCore.QRect(270, 120, 281, 33))
        self.projectNameLine.setObjectName("projectNameLine")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 101, 75, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(271, 10, 168, 34))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 71, 51))
        self.label_4.setObjectName("label_4")
        self.chooseWWWButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseWWWButton.setGeometry(QtCore.QRect(740, 240, 31, 33))
        self.chooseWWWButton.setObjectName("chooseWWWButton")
        self.projrctWWWrLine = QtWidgets.QLineEdit(self.centralwidget)
        self.projrctWWWrLine.setGeometry(QtCore.QRect(270, 240, 461, 33))
        self.projrctWWWrLine.setObjectName("projrctWWWrLine")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 220, 101, 17))
        self.label_5.setObjectName("label_5")
        self.hostLine = QtWidgets.QLineEdit(self.centralwidget)
        self.hostLine.setGeometry(QtCore.QRect(560, 120, 211, 33))
        self.hostLine.setObjectName("hostLine")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(560, 100, 75, 17))
        self.label_6.setObjectName("label_6")
        self.radioExistFolder = QtWidgets.QRadioButton(self.centralwidget)
        self.radioExistFolder.setGeometry(QtCore.QRect(260, 60, 141, 23))
        self.radioExistFolder.setObjectName("radioExistFolder")
        self.radioGit = QtWidgets.QRadioButton(self.centralwidget)
        self.radioGit.setGeometry(QtCore.QRect(410, 60, 141, 23))
        self.radioGit.setObjectName("radioGit")
        self.repositoryLine = QtWidgets.QLineEdit(self.centralwidget)
        self.repositoryLine.setGeometry(QtCore.QRect(560, 55, 211, 33))
        self.repositoryLine.setObjectName("repositoryLine")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(560, 30, 101, 17))
        self.label_7.setObjectName("label_7")
        self.createProjectButton = QtWidgets.QPushButton(self.centralwidget)
        self.createProjectButton.setGeometry(QtCore.QRect(270, 290, 171, 33))
        self.createProjectButton.setObjectName("createProjectButton")
        self.refreshHostsButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshHostsButton.setGeometry(QtCore.QRect(10, 290, 211, 33))
        self.refreshHostsButton.setObjectName("refreshHostsButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python3 LAMP GUI MANAGER v0.0.1"))
        self.chooseFolderButton.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Project folder(if git Projects folder)"))
        self.label_2.setText(_translate("MainWindow", "Project name"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Project create</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Hosts</span></p></body></html>"))
        self.chooseWWWButton.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "public_html/www"))
        self.label_6.setText(_translate("MainWindow", "Host name"))
        self.radioExistFolder.setText(_translate("MainWindow", "From existing folder"))
        self.radioGit.setText(_translate("MainWindow", "From git repository"))
        self.label_7.setText(_translate("MainWindow", "Git link (only ssh)"))
        self.createProjectButton.setText(_translate("MainWindow", "Create"))
        self.refreshHostsButton.setText(_translate("MainWindow", "Refresh Hosts"))

